# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI (CONDA)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: lpqtree-env
        python-version: ${{ matrix.python-version }}
        channels: defaults,conda-forge
        use-only-tar-bz2: true
    - name: Install dependencies
      shell: pwsh
      run: |
        conda install --yes -n lpqtree-env flake8 pytest
        conda install --yes -n lpqtree-env --file=requirements-test.txt
        conda install --yes -n lpqtree-env -c conda-forge libstdcxx-ng
        # - name: Lint with flake8
        #   shell: pwsh
        #   run: |
        #     # stop the build if there are Python syntax errors or undefined names
        #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: pwsh
      run: |
        conda activate lpqtree-env
        pip install -e .
        pytest -svv tests/
