# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI (PIP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 5 * 0' # 1 per month

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools pip pybind11 --upgrade
    - name: Install package
      run: |
        pip install -e .
    - name: Install test requirements
      run: |
        pip install -r requirements-test.txt
    - name: Test with pytest
      if: ${{ matrix.python-version != '3.8' || matrix.os != 'ubuntu-latest' }}
      run: |
        pytest -svv tests
    - name: Run pytest and coverage
      if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
      run: |
        coverage run -m pytest -svv  tests # Run the tests and check for test coverage.
        # coverage report -m  # Generate test coverage report.
        # codecov  # Upload the report to codecov
